### ISSUE TITLE
Cant set it up

### ISSUE THREAD

**Issue by ghost** [agarzon/dnsbl#1]
I setted it up finally and everything seems working , dunno https://dnsbl.aspircd.com however doesnt show result , everything is up to date!

**Comment by agarzon** [comment]
No errors in log? did you enabled php debugging?, did you installed the dependencies with composer?

**Comment by ghost** [comment]
There are no logs been created ever since , logs/ is empty , I get this error in my composer when I run it for long time [symfony\component\process\exception\processtimedoutexception] the process "php -s 0.0.0.0:8888 -t public public/index.php" exceeded the timeout of 300 seconds and I didn’t enable php debuggging , how to enable it? However I have installed dependencies with composer

**Comment by ghost** [comment]
@agarzon yes, please tell I am not sure to how to enable php debugging , while dependencies are installed via composer, I am not sure why the logs are not being created. Also when I run composer start , it tells me this only “php -s 0.0.0.0:8888 -t public public/index.php” and nothing else.

**Comment by agarzon** [comment]
To enable debug:

```
ini_set('display_startup_errors', 1);
ini_set('display_errors', 1);
error_reporting(-1);
```
Add those lines in the main file from this application.

The application must be installed to using Apache or Nginx, using the built in web server from php wont work for this specific application. (due the friendly url).

The logs will be coming from your web server application (apache or nginx).

**Comment by ghost** [comment]
@agarzon add those lines where? Will this fix the issue?

**Comment by ghost** [comment]
also what about the error I get in composer ? I am already running apache2

**Comment by agarzon** [comment]
I don't know about that, this project is already 3 years old, probably some dependencies are dead already

Those lines wont fix the issue. It will help to debug PHP in case there is any error.

**Comment by ghost** [comment]
I won’t be working on this again

**Comment by ghost** [comment]
Closing the issue.
